import { Booking } from '../components/BookingCard';

export const MOCK_USER = {
  id: 'u_001',
  name: 'Rahul Sharma',
  phone: '+91 98765 43210',
  email: 'rahul.sharma@gmail.com',
  level: 1 as 1 | 2 | 3,
  totalSaved: 12400,
  totalTrips: 8,
  avatarInitials: 'RS',
};

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk_001',
    from: 'Mumbai',
    to: 'Pune',
    date: '28 Mar 2026',
    status: 'in_transit',
    price: 4290,
    driverName: 'Ramesh Kumar',
    driverRating: 4.8,
    vehicleType: 'Mini Truck',
    bookingRef: 'BT-2026-001',
  },
  {
    id: 'bk_002',
    from: 'Delhi',
    to: 'Jaipur',
    date: '25 Mar 2026',
    status: 'delivered',
    price: 6750,
    driverName: 'Suresh Yadav',
    driverRating: 4.6,
    vehicleType: 'LCV',
    bookingRef: 'BT-2026-002',
  },
  {
    id: 'bk_003',
    from: 'Bangalore',
    to: 'Chennai',
    date: '20 Mar 2026',
    status: 'delivered',
    price: 8200,
    driverName: 'Vijay Nair',
    driverRating: 5.0,
    vehicleType: 'HCV',
    bookingRef: 'BT-2026-003',
  },
  {
    id: 'bk_004',
    from: 'Hyderabad',
    to: 'Nagpur',
    date: '15 Mar 2026',
    status: 'delivered',
    price: 11500,
    driverName: 'Abdul Karim',
    driverRating: 4.4,
    vehicleType: 'Trailer',
    bookingRef: 'BT-2026-004',
  },
  {
    id: 'bk_005',
    from: 'Ahmedabad',
    to: 'Surat',
    date: '10 Mar 2026',
    status: 'cancelled',
    price: 2800,
    driverName: 'Manoj Patel',
    driverRating: 4.2,
    vehicleType: 'Mini Truck',
    bookingRef: 'BT-2026-005',
  },
  {
    id: 'bk_006',
    from: 'Kolkata',
    to: 'Bhubaneswar',
    date: '5 Mar 2026',
    status: 'delivered',
    price: 9300,
    driverName: 'Debashis Roy',
    driverRating: 4.7,
    vehicleType: 'LCV',
    bookingRef: 'BT-2026-006',
  },
];

export const ACTIVE_BOOKING = MOCK_BOOKINGS[0];

export const TRACKING_CHECKPOINTS = [
  { id: 1, label: 'Pickup Confirmed', time: '09:15 AM', done: true },
  { id: 2, label: 'Goods Loaded', time: '09:45 AM', done: true },
  { id: 3, label: 'In Transit', time: '10:30 AM', done: true },
  { id: 4, label: 'Near Destination', time: '—', done: false },
  { id: 5, label: 'Delivered', time: '—', done: false },
];
